### PR TITLE
branch commit of login/register routes

### PR DESCRIPTION
**Pull request by krystallopez**
Updated commit, initial commit of login/register. Git finally came through so we can do a proper pull request

### CODE REVIEW

**Comment by krystallopez** [comment]
Needs review

**Review by Mariah-Dixon — APPROVED** [review]
Looks good Kystal

**Comment by krystallopez** [comment]
Will merge once db has been created, will need to pull down from main once merged

**Review by l-Rich — APPROVED** [review]
This should fix the bug. Looks great

**Review by MabeDiaby — APPROVED** [review]

**Pull request merged**
